path: /case_${parentIndex}/event_types
views:
  - table: event_types
    alias: t
    connector: db1
    refs:
      - name: evnts
        cardinality: Many
        dataView: events
        'on':
          - column: id
            refColumn: event_type_id

  - table: events
    alias: e
    connector: db2
