init:
  target:
    URL: ssh://localhost
    Credentials: localhost
  appPath: $WorkingDirectory(./../..)
  Ver: $Cat(${appPath}/Version)

pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.17
  build:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - export GO111MODULE=on
      - cd ${appPath}/cmd/datly
      - go mod download
      - go mod tidy
      - export GOOS=linux
      - go build -ldflags="-X 'main.Version=${Ver}'"
      - tar cvzf datly_linux_${Ver}.tar.gz datly
      - export GOOS=darwin
      - go build -ldflags="-X 'main.Version=${Ver}'"
      - tar cvzf datly_darwin_${Ver}.tar.gz datly
      - export GOOS=windows
      - go build -ldflags="-X 'main.Version=${Ver}'"
      - tar cvzf datly_windows_${Ver}.tar.gz datly
