init:
  target:
    URL: ssh://127.0.0.1
    Credentials: localhost
  appPath: $WorkingDirectory(./../..)
  Ver: $Cat(${appPath}/Version)

pipeline:
  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.17
  build:
    action: exec:run
    target: $target
    commands:
      - cd ${appPath}
      - export GOOS=linux
      - go build -ldflags="-X 'main.Version=${Ver}'"
      - tar cvzf datly_linux_${Ver}.tar.gz datly
      - export GOOS=darwin
      - go build -ldflags="-X 'main.Version=${Ver}'"
      - tar cvzf datly_darwin_${Ver}.tar.gz datly
