init:
  appPath: $Pwd(./../..)

  '!gcpCredentials': $params.authWith
  gcp: ${secrets.$gcpCredentials}
  projectID: $gcp.ProjectID
  prefix: $Replace(${projectID},'-','_')
  configBucket: ${prefix}_config
  appName: Datly

pipeline:
  info:
    action: print
    message: $appPath
  uploadRoutes:
    action: storage:copy
    expand: true
    source:
      URL: ${appPath}/gateway/example/routes/
    dest:
      URL: gs://${configBucket}/${appName}/routes/
      credentials: $gcpCredentials
  upload:
    action: storage:copy
    expand: true
    source:
      URL: ${appPath}/gateway/example/resources/
    dest:
      URL: gs://${configBucket}/${appName}/resources/
      credentials: $gcpCredentials
  uploadConfig:
    action: storage:copy
    expand: true
    source:
      URL: ${appPath}/gateway/runtime/gcf/resource/config.json
    dest:
      URL: gs://${configBucket}/${appName}/config.json
      credentials: $gcpCredentials