init:
  AppVersion: $Cat(${appPath}/Version)

pipeline:

  deploy:
    set_sdk:
      action: sdk.set
      target: $target
      sdk: go:1.17

    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - export GO111MODULE=on
        - cd ${appPath}/cmd/datly
        - go mod download
        - go build
        - mv datly /tmp/datly
        - cp /tmp/datly /tmp/datly_utils
        - cd ${appPath}/e2e/local/validator/src
        - go build main/validator.go
        - mv validator /tmp/validator_24
