init:
  i: 0
pipeline:

  loop:
    generate:
      init:
        rule: '${data.gen[$i]}'

      genRule:
        action: exec:run
        description: build datly rule with SQL extension
        target: '$target'
        checkError: true
        commands:
          - pwd
          - cd ${appPath}/e2e/local
          - /tmp/datly -N=${rule.Name} -X=${rule.URL}  -C='mydb|mysql|root:dev@tcp(127.0.0.1:3306)/dev${qMark}parseTime=true' -j='${appPath}/e2e/local/jwt/public.enc|blowfish://default'  -w=autogen ${rule.Args}
          - if [ -d "${appPath}/e2e/local/dsql" ]; then
            rm -r "${appPath}/e2e/local/autogen/dsql_$i";
            mv  "${appPath}/e2e/local/dsql" "${appPath}/e2e/local/autogen/dsql_$i";
            fi

    increment:
      action: nop
      init:
        _: $i++
    goto:
      when: $i < $Len(${data.gen})
      action: goto
      task: loop