init:
  i: 0
  gcpCredURL: 'aws://secretmanager/us-west-1/secret/dev/gcp/${gcpProjectID}'
  URLEncGcpCredURL: $QueryEscape(${gcpCredURL})

pipeline:

  loop:
    generate:
      init:
        rule: '${data.gen[$i]}'

      action: exec:run
      description: build datly rule with SQL extension
      target: '$target'
      checkError: true
      env:
        AWS_SDK_LOAD_CONFIG: true
      commands:
        - cd ${appPath}/e2e/lambda
        - /tmp/datly -N=${rule.Name} -X=${rule.URL}  -C='bqdev|bigquery|bigquery://${gcpProjectID}/bqdev${qMark}credURL=${URLEncGcpCredURL}' -w=autogen

    increment:
      action: nop
      init:
        _: $i++
    goto:
      when: $i < $Len(${data.gen})
      action: goto
      task: loop
  uploadRules:
    clearSetup:
      action: storage:remove
      assets:
        - URL: s3://${configBucket}/${appName}/routes/
          credentials: $awsCredentials
        - URL: s3://${configBucket}/${appName}/dependencies/
          credentials: $awsCredentials
        - URL: s3://${configBucket}/_.cache
          credentials: $awsCredentials

    updatesRoutes:
      action: storage:copy
      source:
        URL: ${appPath}/e2e/lambda/autogen/Datly/routes
      dest:
        URL: s3://${configBucket}/${appName}/routes/
        credentials: $awsCredentials
    updatesDependencies:
      action: storage:copy
      source:
        URL: ${appPath}/e2e/lambda/autogen/Datly/dependencies
      dest:
        URL: s3://${configBucket}/${appName}/dependencies/
        credentials: $awsCredentials


