pipeline:
  fetchDbIP:
    mysqlIp:
      action: docker:inspect
      logging: false
      name: mysqldb1
      post:
        'dbIP.mysql': $Info[0].NetworkSettings.IPAddress

    postgresIP:
      action: docker:inspect
      logging: false
      name: pgdb2
      post:
        'dbIP.pg': $Info[0].NetworkSettings.IPAddress

