tasks: $tasks
pipeline:
  destroy:
    stop-images:
      action: docker:stop
      images:
        - mysql
  run:
    services:
      mysql:
        action: docker:run
        image: mysql:5.7
        name: dbsync
        ports:
          3306: 3306
        env:
          MYSQL_ROOT_PASSWORD: ${mysqlSecrets.Password}
