init:

pipeline:
  bq:
    create:
      action: dsunit:init
      datastore: bqdev
      config:
        driverName: bigquery
        credentials: $bqCredentials
        parameters:
          datasetId: bqdev
      recreate: false
      scripts:
        - URL: ${appPath}/e2e/cloud/datastore/bq/schema.ddl

    prepare:
      action: 'dsunit:prepare'
      datastore: bqdev
      expand: true
      URL: ${appPath}/e2e/cloud/datastore/bq/populate
