views:
  - table: events
    alias: e
    connector: db1
    refs:
      - name: type
        cardinality: One
        dataView: event_types
        'on':
          - column: event_type_id
            refColumn: id

  - table: event_types
    alias: t
    connector: db1
    refs:
      - name: account
        cardinality: One
        dataView: accounts
        'on':
          - column: account_id
            refColumn: id

  - table: accounts
    alias: a
    connector: db1
