init:
 appPath: $Pwd(./../../..)

 '!gcpCredentials': $params.authWith
 gcp: ${secrets.$gcpCredentials}
 projectID: $gcp.ProjectID
 prefix: $Replace(${projectID},'-','_')
 configBucket: ${prefix}_config
 appName: Datly

pipeline:
 info:
  action: print
  message: $appPath
 uploadConfig:
   action: storage:copy
   expand: true
   source:
    URL: ${appPath}/gateway/runtime/gcf/resource/config.json
   dest:
      URL: 'gs://${configBucket}/${appName}/config.json'
      credentials: $gcpCredentials

 deploy:
  action: gcp/cloudfunctions:deploy
  credentials: $gcpCredentials
  '@name': datly
  environmentVariables:
   CONFIG_URL: 'gs://${configBucket}/${appName}/config.json'
  timeout: 540s
  members:
   - user:${env.USER}@vindicotech.com

  availableMemoryMb: 256
  entryPoint: Handle
  runtime: go116
  retry: true
  serviceAccountEmail: ${gcp.serviceAccount}
  source:
   URL: ${appPath}/
