init:
  parentPath: $parent.path
pipeline:

  testUnauthorized:
    signJWT:
      action: secret:signJWT
      privateKey:
        URL: ${appPath}/e2e/cloud/jwt/private.enc
        Key: blowfish://default
      claims:
        userID: 1
        Username: Tester
        email: tester@viantint.com

    printToken:
      action: print
      message: Bearer ${signJWT.TokenString}

    test:
      action: http/runner:send
      requests:
        - Method: POST
          URL: http://127.0.0.1:8080/v1/api/dev/basic/user_acl
          Header:
            Authorization: Bearer ${signJWT.TokenString}
          JSONBody:
            name: ''
            eventsPerformance:
              - Price: 125
              - Price: 250
          Expect:
            Code: 400


  testAuthorized:
    signJWT:
      action: secret:signJWT
      privateKey:
        URL: ${appPath}/e2e/cloud/jwt/private.enc
        Key: blowfish://default
      claims:
        userID: 2
        Username: Developer
        email: dev@viantint.com

    printToken:
      action: print
      message: Bearer ${signJWT.TokenString}

    test:
      action: http/runner:send
      requests:
        - Method: POST
          URL: http://127.0.0.1:8080/v1/api/dev/basic/user_acl
          Header:
            Authorization: Bearer ${signJWT.TokenString}
          JSONBody:
            name: ''
            eventsPerformance:
              - Price: 125
              - Price: 250
          Expect:
            Code: 200


