pipeline:

  getAwsEndpointURL:
    when: $runOnAws
    action: lambda/apigateway:getRestAPI
    '@name': DataAPI
    credentials: $awsCredentials
    post:
      awsEndpointURL: ${EndpointURL}

  test:
    tag: $pathMatch
    description: '@info'
    subPath: 'cases/${index}_*'
    range: 1..006
    template:
      setVars:
        action: nop
        comments: use case init
        skip: $HasResource(${path}/skip.txt)


      test:
        when: $HasResource(${path}/test.yaml)
        action: run
        request: '@test'


    post-test-sleep:
      action: nop
      sleepTimeMs: 1000
      comments: sleep for extra debuging
