templateURL: ../../tmpl/case_${parentIndex}/events.yaml
Path: /case_${parentIndex}/events/{id}/type
output:
  - dataView: event_types
views:
  - name: event_types
    criteria:
      expression: id IN (SELECT event_type_id FROM events WHERE id = ${id})
