path: /case_${parentIndex}/events_and_types
output:
  - dataView: events
  - dataView: event_types
    key: types

views:
  - table: events
    connector: db1

  - table: event_types
    connector: db1
