init:
  i: 0
pipeline:

  loop:
    generate:
      init:
        rule: '${data.gen[$i]}'

      action: exec:run
      description: build datly rule with SQL extension
      target: '$target'
      checkError: true
      commands:
        - cd ${appPath}/e2e/cloud
        - /tmp/datly -N=${rule.Name} -X=${rule.URL}  -C='mydb|mysql|root:dev@tcp(127.0.0.1:3306)/dev${qMark}parseTime=true'   -C='bqdev|bigquery|bigquery://${gcpProjectID}/bqdev${qMark}credURL=gcp%3A%2F%2Fsecretmanager%2Fprojects%2Fviant-e2e%2Fsecrets%2Fe2eCred' -j='${appPath}/e2e/cloud/jwt/public.enc|blowfish://default'  -w=autogen

    increment:
      action: nop
      init:
        _: $i++
    goto:
      when: $i < $Len(${data.gen})
      action: goto
      task: loop