path: /v1/api/invoices

views:
  - table: invoices
    refs:
      - name: items
        dataView: invoice_items
        cardinality: Many
        'on':
          - column: id
            refColumn: invoice_id
      - name: customer
        dataView: customers
        cardinality: One
          'on':
            - column: customer_id
              refColumn: id

  - table: invoice_item
    refs:
      - name: product
        dataView: products
        cardinality: One
          'on':
              - column: product_id
                refColumn: id

  - table: products
    refs:
      - name: vendor
        dataView: vendors
        cardinality: One
         'on':
           - column: vendor_id
             refColumn: id

  - table: vendors

  - table: customer