init:
  appPath: $WorkingDirectory(./../..)
pipeline:
  stop:
    action: process:stop
    target: $target
    input: datly_utils

  start:
    action: process:start
    sleepTimeMs: 3000
    target: $target
    directory: /tmp/
    checkError: true
    immuneToHangups: true
    command: ./datly_utils -c=$appPath/regression/utils/autogen/Datly/config.json -p=8090 > datly_utils_log.txt