init:
  parentPath: $parent.path
  expect: $LoadJSON('${parentPath}/expect.json')

pipeline:

  test:
    action: http/runner:send
    requests:
      - Method: GET
        URL: http://127.0.0.1:8080/v1/api/dev/meta/districts?IDs=1,2
        Expect:
          Code: 200
          JSONBody: $expect